// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'connections-empty-state'
  | 'connections-error-state'
  | 'connections-mindmap-label'
  | 'connections-no-links-state'
  | 'connections-section-head-text'
  | 'connections-section-sidenav-tooltip'
  | 'menuitem-mindmap-open'
  | 'mindmap-tab-title'
  | 'preferences-add-button'
  | 'preferences-cancel-button'
  | 'preferences-column-directional'
  | 'preferences-column-label'
  | 'preferences-delete-button'
  | 'preferences-delete-confirm-title'
  | 'preferences-delete-confirm-unknown'
  | 'preferences-delete-confirm-used'
  | 'preferences-directional-no'
  | 'preferences-directional-yes'
  | 'preferences-edit-button'
  | 'preferences-field-directional'
  | 'preferences-field-label'
  | 'preferences-heading'
  | 'preferences-pane-label'
  | 'preferences-save-button'
  | 'startup-begin'
  | 'startup-finish';
