// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'add-link-button'
  | 'add-link-direction-backward'
  | 'add-link-direction-forward'
  | 'add-link-direction-label'
  | 'add-link-name-label'
  | 'add-link-save-button'
  | 'add-link-target-placeholder'
  | 'add-link-type-label'
  | 'connections-empty-state'
  | 'connections-error-state'
  | 'connections-mindmap-label'
  | 'connections-no-links-state'
  | 'connections-section-head-text'
  | 'connections-section-sidenav-tooltip'
  | 'menuitem-mindmap-open'
  | 'mindmap-tab-title'
  | 'startup-begin'
  | 'startup-finish';
