// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'connections-empty-state'
  | 'connections-error-state'
  | 'connections-mindmap-label'
  | 'connections-no-links-state'
  | 'connections-remove-link-button'
  | 'connections-remove-node-button'
  | 'connections-section-head-text'
  | 'connections-section-sidenav-tooltip'
  | 'menuitem-mindmap-open'
  | 'mindmap-tab-title'
  | 'startup-begin'
  | 'startup-finish';
